SELECT P.PRODUCT_CODE, SUM(P.PRICE * S.TOTAL) AS SALES
FROM PRODUCT P
JOIN (
    SELECT PRODUCT_ID, SALES_AMOUNT AS TOTAL
    FROM OFFLINE_SALE
) S ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;
